### ISSUE TITLE
(Weights Visualisation) How to get output from the Dense layer after activation to feed it into another classifier?

### ISSUE THREAD

**Issue by ibrahim-amer** [julienr/ipynb_playground#2]
Thanks sir for this awesome work!. Actually I've been looking for something like this for quite long time, so thank you . I have a question if you allow me, If I have a test image and I want to get the model output after activation of the dense layer, so in this case what will be the input of this layer ( K.function(inputs, [convout1.output])) ? the original test image ? or the image after computing the output of all the previous layers? shall I compute them by myself or it will be computed implicitly if the test image fed directly into the dense layer?

**Comment by julienr** [comment]
So when creating your model, you would need to keep the activation layer in a `act1` variable.
```
model.add(Dense(32*196, 128))
act1 = Activation('relu')
model.add(act)
```
And then you create the function in a similar way as what you do for convolutions 
```
actout1_f = theano.function([model.get_input(train=False)], act1.get_output(train=False))
```

The input is always the initial image and the model automatically applies the previous layers.
