### ISSUE TITLE
Where can I get the weight: mnist_cnn_weights_v1.hdf?

### ISSUE THREAD

**Issue by matchifang** [julienr/ipynb_playground#3]
Hello @julienr , thank you so much for your contribution on visualisation of the neural network.
I've been following [this link](https://github.com/julienr/ipynb_playground/blob/master/keras/convmnist/keras_cnn_mnist_v1.ipynb) which uses the weights from mnist_cnn_weights_v1.hdf, however, I was unable to find the file in your repository. Could you point me to the link or where I can get it? 
Thank you :)

**Comment by julienr** [comment]
Well, it's saved after training (see the if in cell 9 of this notebook). So if it doesn't exist, the notebook will train the model and then create that file.
